# The nutrition value this food provides.
nutrition: 0
# The saturation this food provides.
saturation: 0.0
# Whether the food can always be eaten, or only when hungry.
can_always_eat: true
# The time it takes for the food to be consumed, in ticks.
consume_time: 40
# The item stack that remains after the food is consumed.
remains: "minecraft:glass_bottle"
animation: "drink"
sound: "generic_drink"
# A list of effects to apply to the player when this food is consumed.
possible_effects:
  - type: absorption
    duration: 1200
    amplifier: 0
    ambient: true
    particles: true
    icon: true
    probability: 1.0
