# Tools Options
tool_level: minecraft:netherite
tool_category: farmersdelight:knife
break_speed: 1.5
attack_damage: 5.5
attack_speed: 2.0
can_sweep_attack: false
can_break_blocks_in_creative: false

# Damageable Options
max_durability: 2031
item_damage_on_attack_entity: 3
item_damage_on_break_block: 1
repair_ingredient: "minecraft:netherite_ingot"

# Enchantable Options
enchantment_value: 16
supported_enchantments:
  - minecraft:sharpness
  - minecraft:smite
  - minecraft:bane_of_arthropods
  - minecraft:knockback
  - minecraft:fire_aspect
  - minecraft:looting
  - minecraft:vanishing_curse
  - minecraft:unbreaking